Added lottery hw
InnaLogvin/ILogvinJavaBase23Sep pull request #1
Opened 2023-10-10 11:43 UTC by InnaLogvin

2023-10-10 17:25 UTC, JIeIIIa requested changes
З нашої предметної області ми знаємо, що працюємо не просто з масивами, а з квитками. Чому б тоді в назвах параметрів в методах не використати цей факт?;)

2023-10-10 17:25 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Lottery.java
> +        for (int i = 0; i < arrayCompany.length; i++) {
На оцінку це не впливало, але подумай що буде у випадку, коли масиви мають різну довжину.

2023-10-10 17:25 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Lottery.java
> +
Я казав, що після генерації потрібно виводити "сирі" дані. Інакше як я, запустивши програму, можу впевнитись, що під час сортування не втратились дані? Також з цього випливає логічне питання: як ти тестувала, що програма працює вірно? Виправ, будь ласка.

2023-10-11 08:13 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/Lottery.java
> +
Додала вивід сирих чисел, але залишила й вивід відсортованих. Бо інакше я не розумію, чи сортування працює

2023-10-11 10:11 UTC, JIeIIIa approved these changes

2023-10-11 14:30 UTC, InnaLogvin commented
Added lottery hw, final version

2023-10-11 14:30 UTC, InnaLogvin commented
Added lottery hw, final version

2023-10-11 14:30 UTC, closed without merging