Lesson13 hw18
InnaLogvin/ILogvinJavaBase23Sep pull request #12
Opened 2023-11-04 15:28 UTC by InnaLogvin

2023-11-05 09:42 UTC, JIeIIIa requested changes

2023-11-05 09:42 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    private Point a;
імена точок ні про що не кажуть і їх просто сплутати

2023-11-05 09:42 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +        expectedDistance = 1.4142135623730951; // ОР расстояние между a и b
дане значення використовується менш, ніж в половині тестів. Який сенс тоді мати його в методі BeforEach?
Якщо не хочеш вказувати це у тестах, то доцільніше було зробити статичну константу

2023-11-05 09:42 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +        double actualDistance = Point.distanceBetween(c, b);
тут мені потрібно додатково пам'ятати що c == null. простіше було зробити:
```
double actualDistance = Point.distanceBetween(null, b);
```

2023-11-05 09:42 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    void distanceToTest() {// проверка на равность расстояния из ОР и из метода
має бути аналогічний тест, який перевіряє
```
point.distanceTo(null)
```

2023-11-06 09:41 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    private Point a;
pointA, pointA

2023-11-06 09:44 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +        expectedDistance = 1.4142135623730951; // ОР расстояние между a и b
private final double EXPECTEDDISTANCE

2023-11-06 09:46 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +        double actualDistance = Point.distanceBetween(c, b);
удалила с и d

2023-11-06 09:52 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    void distanceToTest() {// проверка на равность расстояния из ОР и из метода
distanceToNullTest

2023-11-06 19:06 UTC, JIeIIIa requested changes

2023-11-06 19:06 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    private final double EXPECTEDDISTANCE = 1.4142135623730951;
`UPPER_SNAKE_CASE` же ж

2023-11-06 19:06 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    private Point a;
стало гірше( зараз додався префікс, який  при читанні коду ігнорується (оскільки всі точки починаються з `point*`

2023-11-07 08:05 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    private Point a;
aPoint/bPoint

2023-11-07 08:06 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    private final double EXPECTEDDISTANCE = 1.4142135623730951;
EXPECTED_DISTANCE

2023-11-07 08:48 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/classes/PointTest.java
> +    private Point a;
ага, тепер потрібно ігнорувати текст не на початку, а в кінці слова) кожна літера має свою назву (для передачі в радіо ефері). можна було назвати alpha/bravo (див [тут](https://virtually-fluent.com/wp-content/uploads/2020/11/English-Phonetic-Spelling-Alphabet.png)). можна було вигадати щось своє

2023-11-07 08:50 UTC, JIeIIIa approved these changes

2023-11-07 09:48 UTC, merged