Added SquareArray class and test
InnaLogvin/ILogvinJavaBase23Sep pull request #13
Opened 2023-11-05 10:14 UTC by InnaLogvin

2023-11-05 12:54 UTC, JIeIIIa requested changes

2023-11-05 12:54 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +        squareMatrix = new int[][]{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
В даний метод є сенс щось виносити тільки, якщо елементи спільні для всіх тестів (або ж майже для всіх). Якісь налаштування, які ти робиш завжди. В твоєму ж випадку налаштування потрібні тільки для половини тестів.

2023-11-05 12:54 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +    void calculateAverageTest() {
В завданні малось на увазі середнє для одновимірного масиву, але твій варіант має право на життя.
Тестами не покриті наступні варіанти (нижче приклад вхідних даних):
```
SquareArray.calculateAverage(null);
SquareArray.calculateAverage(new int[][]{});
SquareArray.calculateAverage(new int[][]{{}, {}, {}});
SquareArray.calculateAverage(new int[][]{{1, 2, 3}, {4, 5}, {6}});
SquareArray.calculateAverage(new int[][]{{1, 2, 3}, null, {7, 8, 9});
```

2023-11-05 12:54 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +        assertEquals(expectedIsSquare, actualSquare);
Не потрібно порівнювати `boolean` змінну через `assertEquals`. Натомість використовуй методи `assertTrue`/`assertFalse`

2023-11-05 12:54 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +        boolean expectedIsSquare = false;
Тобто в `BeforeEach` ти змінній присвоєла значення, а тут змінила... навіщо так?(

2023-11-05 12:54 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +}
Не вистачає тестів, які б перевіряли чи є наступні матриці квадратними
```
SquareArray.isSquareMatrix(null);
SquareArray.isSquareMatrix(new int[][]{});
SquareArray.isSquareMatrix(new int[][]{{}, {}, {}});
SquareArray.isSquareMatrix(new int[][]{{1, 2, 3}, {4, 5}, {6}});
SquareArray.isSquareMatrix(new int[][]{{1, 2, 3}, null, {7, 8, 9});
```
Хоча вхідні матриці я вказав ті ж саме, але це мають бути окремі тести

2023-11-06 10:24 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +        squareMatrix = new int[][]{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
прибрала метод

2023-11-06 10:27 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +        assertEquals(expectedIsSquare, actualSquare);
залишила 1 тест isSquareMatrixTest

2023-11-06 10:27 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +        boolean expectedIsSquare = false;
видалила таке

2023-11-07 08:29 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +    void calculateAverageTest() {
додано

2023-11-07 08:29 UTC, InnaLogvin commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +}
додано

2023-11-07 09:03 UTC, JIeIIIa requested changes

2023-11-07 09:03 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/beforeoop/SquareArray.java
> +        boolean isNan = false;
Ця змінна зайва. Якщо ти кажеш, що середнє не визначено у випадку, коли один з рядків `null`, то одразу повертай результат з методу. Навіщо переривати цикл і після циклу робити перевірку чи коректно цикл закінчился?
```
for (int i = 0; i < matrix.length; i++) {
    if (matrix[i] == null) {
        return Double.NaN;
    }
    for (int j = 0; j < matrix[i].length; j++) {
        sum += matrix[i][j];
        totalElements++;
    }
}
return (double) sum / totalElements;
```

2023-11-07 09:03 UTC, JIeIIIa commented on src/test/java/ua/vodafone/homeworks/beforeoop/SquareArrayTest.java
> +        assertTrue(SquareArray.isSquareMatrix(new int[][]{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}));
Краще не мішати асерт та код, який тестується. Взагалі раджу розбивати тести на блоки given/when/then і відокремлювати таки блоки порожнім рядком (навіть, якщо не вставляєш відповідні коментарі(

2023-11-07 09:43 UTC, InnaLogvin commented on src/main/java/ua/vodafone/homeworks/beforeoop/SquareArray.java
> +        boolean isNan = false;
дякую, змінила

2023-11-07 09:47 UTC, merged