VendingMachine
InnaLogvin/ILogvinJavaBase23Sep pull request #15
Opened 2023-11-10 19:07 UTC by InnaLogvin

2023-11-11 06:46 UTC, JIeIIIa requested changes

2023-11-11 06:46 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachine.java
> +        private final int order;
Це поле зайве. У всіх enum'ів є метод, який повертає аналогічне значення

```
    /**
     * Returns the ordinal of this enumeration constant (its position
     * in its enum declaration, where the initial constant is assigned
     * an ordinal of zero).
     *
     * Most programmers will have no use for this method.  It is
     * designed for use by sophisticated enum-based data structures, such
     * as {@link java.util.EnumSet} and {@link java.util.EnumMap}.
     *
     * @return the ordinal of this enumeration constant
     */
    public final int ordinal() { ... }
```

2023-11-11 06:46 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +            int userChoice = scanner.nextInt();
Вводити потрібно саме назву напою. Інакше практики з `valueOf` не буде. Ну і звичніше замовляти чай/каву, а не позицію 1 та 3, наприклад;)

2023-11-11 06:46 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +        if (totalDrinks > 1) {
```
if (totalDrinks > 1) {
    totalAmount = -1_000_000; // як статити мільйонером :D
    System.out.println("You've ordered " + totalDrinks + " drinks.");
    System.out.println("Total amount to pay: " + totalAmount + " UAH.");
}
```
Інкапсуляція - це як раз про те, щоб не було несанкціонованих змін. Зараз ти на користувача покладаєш обовʼязок підрахунку статистики замовлення.
До того ж метод main містить дуже багато логіки: друк меню, ввід даних, безпосередньо замовлення, вивід інформації про замовлення. Це я до того, що потрібно було розбити все на окремі методи. 

Перенеси роботу з замовленням в окремий клас, а у Runner-класі викликай відповідні методи.

2023-11-11 06:46 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachine.java
> +        return null;
Ми вже знаємо про Exception. Тут би краще кинути
```
throw new IllegalArgumentException("Unexpected drink");
```
Дана ситуація може виникнути коли в enum щось додали, а додати рецепт забули

Або ж повертай `return "Don't know how to make a drink: " + drink` Але врахуй, що грошей за даний напій брати не потрібно

2023-11-11 06:46 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachine.java
> +    String chooseDrinks(Drinks drink) {
В цьому ж методі ти насправді не напої обираєш, а для конкретного напою повертаєш рецепт приготування. Назва методу не відповідає його суті.

2023-11-11 06:46 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +public class VendingMachineRunner {
Зроби, будь ласка, якийсь підпакет і перенеси даний клас у нього. Так щоб runner-клас і решта класів були у різних пакетах. Питання через те, що "машиною" має користуватись будь-хто, але публічного API я не побачив

2023-11-11 06:46 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +                System.out.println(message);
Тут вивід в консоль зараз може бути `null`

2023-11-14 17:36 UTC, InnaLogvin commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachine.java
> +        private final int order;
видалено

2023-11-14 18:14 UTC, InnaLogvin commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +            int userChoice = scanner.nextInt();
String userChoice = scanner.nextLine().toLowerCase();

2023-11-14 18:19 UTC, InnaLogvin commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachine.java
> +    String chooseDrinks(Drinks drink) {
preparingDrinks

2023-11-14 18:54 UTC, InnaLogvin commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +        if (totalDrinks > 1) {
executeOrder
printOption

2023-11-14 18:55 UTC, InnaLogvin commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachine.java
> +        return null;
throw new IllegalArgumentException("Unexpected drink");

2023-11-14 19:07 UTC, InnaLogvin commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +public class VendingMachineRunner {
готово

2023-11-14 22:36 UTC, JIeIIIa commented on src/main/java/ua/vodafone/homeworks/classes/VendingMachineRunner.java
> +        if (totalDrinks > 1) {
Трішки не те на що я розраховував. Ти всю логіку перенесла у `VendingMachine`. Де ж тут "розподіл обовʼязків"? До того ж якщо ти захочеш завтра приймати замовлення через інтернет (а не з консолі), то потрібно буде код продублювати. Натомість що я пропоную:

`VendingMachine`: відповідає тільки за замовлення напоїв. Тобто може містити методи: 
```
public String printMenu() { ... }

public void order(Drink drink) { ... } // addToOrder - метод, який додає напій у замовлення. тут доцільно розмістити switch та логіку по оборахунку загальної вартості та кількості напоїв

public void printBill() { ... }
```
Це буде публічний  API за допомогою якого інші класи будуть взаємодіяти з `VendingMachine`. Якщо потрібні якісь додаткові методи, то вони мали б бути private

Логіка по зчитуванню даних з консолі і "розумінню" чого хоче користувач мала б бути у Раннері. Таким чином у тебе буде клас, який взаємодіє з користувачам і на основі цього "використовує" автомат з напоями.
В такій реалізації ти зіткнешся з проблемою, що Раннер не може у автомат з напоями передати змінну типу Drinks. Тому Напої я б зробив публічним enum'ом

2023-11-19 09:44 UTC, merged