Lesson7hw11
InnaLogvin/ILogvinJavaBase23Sep pull request #2
Opened 2023-10-11 14:58 UTC by InnaLogvin

2023-10-11 16:00 UTC, JIeIIIa requested changes

2023-10-11 16:00 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Matrix.java
> +        for (int i = 0; i < rows; i++) {
Для 45-го рядка використання `rows` виправдано. Але тут, я б радив все одно звертатись до `matrix.length`

2023-10-11 16:00 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Matrix.java
> +        for (int i = 0; i < rows; i++) {
Не потрібно так робити. Кожен раз коли ти ітеруєшся по масиву використовуй поле `length`. Завта рядком вище я згенерую матрицю так:
```
int[][] matrix = new int[2 *  rows][10 * cols];
```
де гарантія, що не забуду ще цикл змінити?

2023-10-11 16:00 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Matrix.java
> +        for (int i = 0; i < reversedMatrix.length; i++) {
Для мене магія в тому, що я не знаю яка була "початкова" матриця)
Тако ж я не розумію який сенс мати метод для друку одновимірного масива. Ми ж працюємо з матрицями і логічно було б мати метод для виводу матриці у консоль.

2023-10-11 16:00 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Matrix.java
> +        int[][] matrix = fillMatrix(row, column);
Назва методу вводить в оману. Тут відбувається не заповнення, а генерація/створення/тощо

2023-10-12 09:32 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/Matrix.java
> +        int[][] matrix = fillMatrix(row, column);
done

2023-10-12 09:33 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/Matrix.java
> +        for (int i = 0; i < reversedMatrix.length; i++) {
згідна, додала вивід початкової матриці та змінила метод

2023-10-12 09:33 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/Matrix.java
> +        for (int i = 0; i < rows; i++) {
done

2023-10-12 09:34 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/Matrix.java
> +        for (int i = 0; i < rows; i++) {
done

2023-10-12 18:13 UTC, JIeIIIa requested changes

2023-10-12 18:13 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Matrix.java
> +            for (int j = 0; j < cols; j++) {
Тобто `rows` ти виправила, а чому тоді `cols` залишила? Ти ж ітеруєшся по елементам в i-му рядку. Тож вкажи це явно у циклі

2023-10-12 19:00 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/Matrix.java
> +            for (int j = 0; j < cols; j++) {
done

2023-10-12 19:31 UTC, JIeIIIa requested changes

2023-10-12 19:31 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/Matrix.java
> +            for (int j = 0; j < cols; j++) {
ти виправили нижче в коді, а тут лишилось без змін(

2023-10-13 08:15 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/Matrix.java
> +            for (int j = 0; j < cols; j++) {
наче кругом виправила тільки що

2023-10-13 11:24 UTC, merged