Added StepArray project
InnaLogvin/ILogvinJavaBase23Sep pull request #3
Opened 2023-10-14 18:18 UTC by InnaLogvin

2023-10-14 19:36 UTC, JIeIIIa requested changes

2023-10-14 19:36 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +            int cols = ThreadLocalRandom.current().nextInt(1, maxCols);
За умовою

>  кількість елементів має бути випадковим числом M* в діапазоні 0 <= M* < M

Чому у тебе від 1?

2023-10-14 19:36 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +    public static void divideElementsByMinValue(int[][] matrix) {
Краще мати метод `divideElementsByValue(int[][] matrix, int value)`. Тому що зараз ти двічі вираховуєш абсолютний мінімум замість того, щоб скористатись вже знайденим значенням. До того ж метод вийде більш універсальним.

2023-10-14 19:36 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +                matrix[i][j] = matrix[i][j] / absoluteMin;
Що буде у випадку `absoluteMin == 0`?

2023-10-14 19:36 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +    public static int findMinValue(int[][] matrix) {
Насправді замість твоїх двох методів можна мати 
```
int[] findMinimims(int[][] matrix) { // для пошуку мінімумів в рядках
   ...
}

int findMinimum(int[] array) { // для пошуку мінімуму в одновимірному масиві
    ...
}
```
Тоді для абсолютного мінімума не потрібно буде перебирати всю матрицю, а можна скористатись наявною інформацією про елементи;)

2023-10-16 10:18 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +    public static int findMinValue(int[][] matrix) {
public static int[] findMinRowValue(int[][] matrix)
public static int findMatrixMinimum(int[] array)
done

2023-10-16 10:18 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +    public static void divideElementsByMinValue(int[][] matrix) {
public static void divideElementsByMinValue(int[][] matrix, int value)
done

2023-10-16 11:38 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +                matrix[i][j] = matrix[i][j] / absoluteMin;
if (matrixMinValue != 0)
fixed

2023-10-16 11:39 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +            int cols = ThreadLocalRandom.current().nextInt(1, maxCols);
fixed
 int cols = ThreadLocalRandom.current().nextInt(0, maxCols);

2023-10-16 23:04 UTC, JIeIIIa requested changes

2023-10-16 23:04 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +        int matrixMinValue = value;
А який сенс в змінній `matrixMinValue`? В коді ж можна використовувати змінну `value` і від цього нічого не змінить. Більше того, я б метод назвав `divideElementByValue` оскільки цьому методу байдуже чи є `value` мінімумом, чи якоюсь довільною змінною

2023-10-16 23:04 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +    public static int findMinValue(int[][] matrix) {
Методи є, але ж код не перевикористовується. Цей шматок робить те саме, що і метод `findMatrixMinimum`
```
int minValue = matrix[i][0];
for (int j = 0; j < matrix[i].length; j++) {
    if (matrix[i][j] < minValue) {
        minValue = matrix[i][j];
    }
}
minRowValue[i] = minValue;
```
Я казав про:
```
    public static int[] findMinRowValue(int[][] matrix) {
        int[] minRowValue = new int[matrix.length];
        for (int i = 0; i < matrix.length; i++) {
            if (matrix[i].length == 0) {
                minRowValue[i] = 0;
            } else {
                minRowValue[i] = findMatrixMinimum(matrix[i]);
            }

        }
        return minRowValue;
    }
```

2023-10-16 23:04 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +                minRowValue[i] = 0;
Якщо мінімума не існує, то потрібно так і сказати користувачу. Чому виводиться 0 я не дуже розумію. Варіантів тут 2: 
1) використати клас обгортку, який дозволить зберегти null
2) зробити константу `private static final int NOT_DEFINED = Integer.MIN_VALUE;` (можна обрати будь-яке число, яке не може зустрітись у матриці). Якщо мін не існує, то записувати значення з цієї константи. При виводі у консоль порівнювати значення з константою і "підміняти" на порожній рядок або якийсь текст

2023-10-17 08:11 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +        int matrixMinValue = value;
matrixMinValue я називала для себе, щоб розуміти, на що ми тут ділення робимо

2023-10-17 11:35 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +        int matrixMinValue = value;
Тобто якщо потрібно буде ще поділити на максимальний елемент, то будемо робити новий метод?

2023-10-17 11:37 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +    public static int findMinValue(int[][] matrix) {
Дане зауваження не враховано. Я ж навіть приклад коду навів (

2023-10-17 11:43 UTC, JIeIIIa requested changes

2023-10-17 11:43 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +            if (array[i] != NOT_DEFINED) {
Два `if` виглядають зайвими
```
if (minValue == NOT_DEFINED || (array[i] != NOT_DEFINED && array[i] < minValue)) {
   minValue = array[i];
}
```

2023-10-17 11:43 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/StepArray.java
> +        int matrixMinValue = value;
Тобто якщо потрібно буде ще поділити на максимальний елемент, то будемо робити новий метод?

2023-10-17 14:31 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +        int matrixMinValue = value;
згідна)

2023-10-17 14:34 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +            if (array[i] != NOT_DEFINED) {
поправлено

2023-10-17 14:42 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/StepArray.java
> +    public static int findMinValue(int[][] matrix) {
done

public static int[] findMinRowValue(int[][] matrix) {
        int[] minRowValue = new int[matrix.length];
        for (int i = 0; i < matrix.length; i++) {
            if (matrix[i].length == 0) {
                minRowValue[i] = NOT_DEFINED;
            } else {
                minRowValue[i] = findMatrixMinimum(matrix[i]);
            }
        }
        return minRowValue;
    }

2023-10-17 14:44 UTC, merged