Added FitnessTrackerUser and FitnessTrackerRunner
InnaLogvin/ILogvinJavaBase23Sep pull request #7
Opened 2023-10-19 14:07 UTC by InnaLogvin

2023-10-19 21:58 UTC, JIeIIIa requested changes

2023-10-19 21:58 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/FitnessTrackerUser.java
> +    private static final int YEAR = 2023;
Молодець, що створила окрему константу. Тим саме з коду стає зрозуміліше, що це за число.
Але на лекції ми проговорювали, що спочатку описуємо статичні константи, статичні змінні, потім поля класу, далі конструктори, гетери/сетери і після цього решта методів. Давай дотримуватись такої структури;)

2023-10-19 21:58 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/FitnessTrackerUser.java
> +        int age;
немає сенсу розділяти оголошення та ініціалізацію змінної на різні рядки. краще 
```
int age = YEAR - yearOfBirth;
```
або ж навіть
```
public static int calculateAge(int yearOfBirth) {
   return YEAR - yearOfBirth;
```

2023-10-19 21:58 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/FitnessTrackerRunner.java
> +        user[0].printAccountInfo();
Тут би підійшов for або навіть for each цикл;)

2023-10-20 09:18 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/FitnessTrackerUser.java
> +        int age;
done

2023-10-20 09:18 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/FitnessTrackerUser.java
> +    private static final int YEAR = 2023;
done

2023-10-20 09:22 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/FitnessTrackerRunner.java
> +        user[0].printAccountInfo();
done

2023-10-20 11:59 UTC, JIeIIIa approved these changes

2023-10-20 12:01 UTC, merged