Added point hw
InnaLogvin/ILogvinJavaBase23Sep pull request #8
Opened 2023-10-23 15:14 UTC by InnaLogvin

2023-10-25 08:01 UTC, JIeIIIa requested changes

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +    public int distanceTo(Point another) { //відстань до іншої точки; відстань = √((x2 - x1)² + (y2 - y1)²)
Цілі числа для координат - ок. А чому відстань - це ціле число?

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +    public Object clone() throws CloneNotSupportedException {
Тут потрібно повертати більш спеціалізований тип. Ми ж клонуємо точку, тому і тип повертаємого значення має бути `Point`. А в методі потрібно зробити приведення типу.

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +        System.out.println("a " + a.toString()); //отримати поточні координати
явний виклик метода `toString()` - не обовʼязковий. І про це IDEA мала сповістити (він сірим відображається)

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/PointCalculable.java
> +    public  int distanceBetween(Point one, Point another);
форматування коду

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +        int distanceBetween = fakePoint.distanceBetween(a, b);
Навіщо мені мати третю точко, для знаходження відстані між двома іншими? Ми ж з тобою розбирали це питання... (((

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +    public int distanceBetween(Point one, Point another) {
Що буде, якщо перший та/або другий параметр буде `null`? В Телеграм було окреме зауваження з цього приводу.

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +        System.out.println("Copied fakePoint is " + copiedPoint);
Ти вірно створюєш копію обʼєкту. Але зроби порівняння з оригіналом і покажи а) що обʼєкт дійсно дорівнює оригіналу; б) що це дійсно різні обʼєкти.

2023-10-25 08:01 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +public class Point implements PointCalculable, Cloneable {
Зробила дещо зайве, а про обовʼязкове забула...
Не розумію навіщо тобі інтерфейс `PointCalculable`. Ти ж його ніяк не використовуєш.
Натомість перевизначених `equals` та `hashCode` немає.

2023-10-25 17:52 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +    public int distanceTo(Point another) { //відстань до іншої точки; відстань = √((x2 - x1)² + (y2 - y1)²)
змінила distanceTo та distanceBetween на double

2023-10-25 17:55 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +        System.out.println("a " + a.toString()); //отримати поточні координати
видалила виклик

2023-10-25 18:11 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/PointCalculable.java
> +    public  int distanceBetween(Point one, Point another);
видалила пробіл

2023-10-25 18:11 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +    public Object clone() throws CloneNotSupportedException {
змінила

2023-10-25 18:26 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +        int distanceBetween = fakePoint.distanceBetween(a, b);
видалила фейкпоінт

2023-10-26 12:53 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +    public int distanceBetween(Point one, Point another) {
готово

2023-10-26 12:53 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +        System.out.println("Copied fakePoint is " + copiedPoint);
готово

2023-10-26 12:56 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +public class Point implements PointCalculable, Cloneable {
була якась ідея щодо інтерфейсу, але я вже не можу тепер згадати(

2023-10-26 20:46 UTC, JIeIIIa requested changes

2023-10-26 20:46 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +        if (this == obj) return true;
Я попереджав про автогенерацію і code conventions: де фігурні дужки?

2023-10-26 20:46 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/PointCalculable.java
> +    public double distanceBetween(Point one, Point another);
Це має бути статичний метод класу, т.я. зараз можна зробити виклик:
```
Point redundantPoint = new Point(0, 0);
double result = redundantPoint.distanceBetween(a, b); // навіщо мені третя точка для розрахунку відстані між a та b?
```
Більше того: ми з тобою це питаня розбирали. У в ТГ було:

> JIeIIIa, [23.10.23 21:57]
> як в середині методу звернутись до об'єкту, на якому цей метод викликається?
> 
> JIeIIIa, [23.10.23 21:57]
> (цікаво, що ти це робила на одному зі скрінів)
> 
> Инна Логвин, [23.10.23 21:58]
> ааа зіс?
> 
> JIeIIIa, [23.10.23 21:59]
> бінго. відповідно коли метод не статичний у тебе є третя точка - і це об'єкт, що доступний черз this

Якщо метод не статичний, то є `this` і "поточний об'єкт". Відповідно щоб не було "поточного об'єкту" - потрібно, щоб метод був статичним...

2023-10-26 20:46 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +        int distanceBetween = fakePoint.distanceBetween(a, b);
Проблема ж не в `fakePoint`, а в будь-якому об'єкту, що використовується для виклику...

2023-10-26 20:46 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +    public int distanceBetween(Point one, Point another) {
Не бачу що саме готово(
Має бути перевірка і якщо якийсь з параметрів `null`, то повертаємо невалідне значення -1. Аналогічно, як ми робили для бінарного пошуку.

2023-10-27 08:22 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +        if (this == obj) return true;
if (this == obj) {return true;}
        if (obj == null || getClass() != obj.getClass()) {return false;}

2023-10-27 08:30 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/PointCalculable.java
> +    public double distanceBetween(Point one, Point another);
public static double distanceBetween(Point one, Point another)

2023-10-27 12:15 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/PointCalculable.java
> +    public static double distanceBetween(Point one, Point another){
Цей метод не перевизначається в класі Point і завжди повертає 0. Навіщо він взагалі я не розумію... Звернутись до нього можна через `PointCalculable.distanceBetween(...)`. Щоб краще розібратись, додай у методи sout і подивись коли який метод викликається.
Також форматування коду (де пробіл перед `{`?

2023-10-27 12:15 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +        System.out.println("Distance between a and b: " + distanceBetween(a, b));
В межах класу виклик методу ок. Але якщо захочеш викликати метод з іншого класу, то потрібно робити: `Point.distanceBetween(a, b)`. За помилку я це не рахую

2023-10-27 12:15 UTC, JIeIIIa commented on src/ua/vodafone/homeworks/classes/Point.java
> +        if (this == obj) return true;
Натисни Ctrl+Alt+L (або ж Command+Option+L на Mac) і подивись на результат форматування. Також раджу ще раз передивитись https://www.oracle.com/technetwork/java/codeconventions-150003.pdf (п.7.4 і нижче). На лекції ж не було прикладів коли після `if` в тому ж рядку ідуть фігурні дужки і оператор. Чому тоді зараз ти так пишеш?(

2023-10-27 13:03 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/Point.java
> +        if (this == obj) return true;
public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
так, я забула про форматування

2023-10-27 13:04 UTC, InnaLogvin commented on src/ua/vodafone/homeworks/classes/PointCalculable.java
> +    public static double distanceBetween(Point one, Point another){
видалила метод з інтерфейсу

2023-10-30 08:13 UTC, merged